Current cuda device:  0
/home/swpants05/Desktop/2025_FastMri/Data/train
/home/swpants05/Desktop/2025_FastMri/Data/val
Epoch # 0 ............... varnet_small ...............
/home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/utils/model/varnet.py:286: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at /pytorch/aten/src/ATen/native/TensorCompare.cpp:611.)
  soft_dc = torch.where(mask, current_kspace - ref_kspace, zero) * self.dc_weight
loss file saved! /home/swpants05/Desktop/2025_FastMri/result/varnet_small/val_loss_log
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/main.py", line 82, in main
    train(args)   # utils.learning.train_part.train 호출 :contentReference[oaicite:2]{index=2}
    ^^^^^^^^^^^
  File "/home/swpants05/Desktop/2025_FastMri/2025_GeekSeek/utils/learning/train_part.py", line 196, in train
    wandb.Image(sample_grid,
  File "/home/swpants05/.pyenv/versions/3.11.4/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 266, in __init__
    self._initialize_from_data(data_or_path, mode, file_type, normalize)
  File "/home/swpants05/.pyenv/versions/3.11.4/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 405, in _initialize_from_data
    mode = mode or self.guess_mode(data, file_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swpants05/.pyenv/versions/3.11.4/lib/python3.11/site-packages/wandb/sdk/data_types/image.py", line 603, in guess_mode
    raise ValueError(
ValueError: Un-supported shape for image conversion [2, 384, 384]

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
